import { Link } from 'react-router-dom';
import PageSeo from '../components/PageSeo.jsx';
import { SITE_URL } from '../seo/meta.js';

export default function Privacy() {
  return (
    <>
      <PageSeo
        title="Privacy Policy — Usama Aslam Portfolio & Tools"
        description="Privacy policy for Usama Aslam's portfolio and free browser-based tools. All file processing happens entirely in your browser — no data is ever uploaded."
        path="/privacy"
        robots="noindex, follow"
      />

      <main id="main-content" className="mx-auto max-w-3xl px-4 py-16 sm:px-6 pt-24">
        <nav aria-label="Breadcrumb" className="mb-6 text-sm text-slate-500">
          <Link to="/" className="hover:text-slate-900">Home</Link>
          <span className="mx-2" aria-hidden="true">›</span>
          <span className="text-slate-900">Privacy Policy</span>
        </nav>

        <h1 className="text-3xl font-bold text-slate-950">Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: May 2026</p>

        <div className="mt-8 space-y-8 text-sm leading-7 text-slate-700">
          <section>
            <h2 className="text-lg font-semibold text-slate-950">Overview</h2>
            <p className="mt-2">
              This privacy policy applies to the Usama Aslam portfolio website and tools platform
              hosted at <strong>usama-resumae.netlify.app</strong>. We are committed to protecting
              your privacy. This policy explains what data we collect, how we use it, and your rights.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-950">File processing — no server upload</h2>
            <p className="mt-2">
              All file processing tools (PDF Compressor, PDF Merger, PDF Splitter, Image to PDF,
              Word to PDF, Image Compressor, Image Resizer) process your files{' '}
              <strong>entirely within your browser</strong> using client-side JavaScript libraries.
              Your files are never uploaded to any server, never stored, and never transmitted to
              any third party. Files exist only in your browser's memory during the operation and
              are released when you close or reset the tool.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-950">Data we do not collect</h2>
            <ul className="mt-2 space-y-1 list-disc list-inside">
              <li>File contents or file names from tool usage</li>
              <li>Passwords generated by the Password Generator</li>
              <li>QR code content entered into the QR Code Generator</li>
              <li>JSON data entered into the JSON Formatter</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-950">Contact form</h2>
            <p className="mt-2">
              The contact form collects your name, email address, and message for the purpose of
              responding to your inquiry. This data is not shared with third parties and is used
              solely for communication.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-950">Analytics</h2>
            <p className="mt-2">
              This site may use anonymized analytics to understand page traffic. No personally
              identifiable information is collected through analytics.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-950">Contact</h2>
            <p className="mt-2">
              For privacy-related questions:{' '}
              <a href="mailto:usama24.2r@gmail.com" className="text-blue-600 hover:underline">
                usama24.2r@gmail.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-slate-200 flex gap-4 text-sm">
          <Link to="/terms" className="text-blue-600 hover:underline">Terms of Service</Link>
          <Link to="/tools" className="text-blue-600 hover:underline">Free Tools</Link>
        </div>
      </main>
    </>
  );
}
